### ISSUE TITLE
Checking in

### ISSUE THREAD

**Issue by natseg** [MacnoC/serverless-offline-kms#1]
Hello!

Thank you for creating this repo.
Just checking in 👋 
If we looked at updating dependencies and making this repo generally up-to-date, would you have time to review the PRs?

Thank you!

**Comment by Kratus1985** [comment]
Hi @natseg 

Thanks for use it. Yes, I can review the PRs.

**Comment by Kratus1985** [comment]
Hi @natseg 
I just release the new version.

Regards
